// LOG IN PAGE
const LOGIN_FORM_FIELDS = {
  PHONE: "PHONE",
  EMAIL: "EMAIL",
  VERFI_CODE: "VERFICATION CODE",
  REMEMBER_ME: "REMEMBER ME",
};

const USER_TYPE = {
  NANNY: "NANNY",
  CUSTOMER: "CUSTOMER",
};

const VERFI_CODE_STATUS = {
  SEND: "SEND",
  FREEZE: "FREEZE",
  RESEND: "RESEND",
};

// HIRE FORM
const JOB_TYPE = {};

export default { VERFI_CODE_STATUS, USER_TYPE, LOGIN_FORM_FIELDS };
